        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
        <script type="text/javascript">
		//var geocoder;
 function initialize() {
        var address = (document.getElementById('my-address'));
        var autocomplete = new google.maps.places.Autocomplete(address);
        autocomplete.setTypes(['geocode']);
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                return;
            }

        var address = '';
        if (place.address_components) {
            address = [
                (place.address_components[0] && place.address_components[0].short_name || ''),
                (place.address_components[1] && place.address_components[1].short_name || ''),
                (place.address_components[2] && place.address_components[2].short_name || '')
                ].join(' ');
        }
      });
}
function codeAddress() {
    geocoder = new google.maps.Geocoder();
	 var address = document.getElementById("my-address").value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
		Mage.Cookies.set('latSearch',results[0].geometry.location.lat());
		Mage.Cookies.set('longSearch',results[0].geometry.location.lng())
      alert("Latitude: "+results[0].geometry.location.lat());
      alert("Longitude: "+results[0].geometry.location.lng());
	  
	  new Ajax.Request('<?php  echo $this->getUrl('searchbylocation/index/saveLastLong')?>', {
		  method:'get',
		  parameters: {
  		  		latSearch: results[0].geometry.location.lat(),
				 longSearch: results[0].geometry.location.lng()
 			 },
		  onSuccess: function(transport) {
			  //alert("amit");
		  },
  		onFailure: function() { console.log('Something went wrong...'); }
	});
	  
      } 

      else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }
function FindLocation(currentElement) {
	console.log(currentElement.value.length);
	if(currentElement.value.length>3){
	//document.getElementById("my-address").setAttribute("disabled", false);
	//document.getElementById('my-address').removeAttribute('disabled');
	// document.getElementById("my-address").value='';
	 initialize();
	}
//google.maps.event.addDomListener(window, 'load', initialize);

} 

 
  function GetGeoLocation() {
  	google.maps.event.addDomListener(window, 'load', initialize);
	if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
    //x.innerHTML = "Latitude: " + position.coords.latitude + 
    //"<br>Longitude: " + position.coords.longitude;	
	codeLatLng(position.coords.latitude,position.coords.longitude)
}
function codeLatLng(lat, lng) {
	var geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(lat, lng);
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
      console.log(results)
        if (results[1]) {
		   document.getElementById("my-address").value=results[3].formatted_address;
		} else {
          alert("No results found");
        }
      } else {
        alert("Geocoder failed due to: " + status);
      }
    });
  }

	 
GetGeoLocation();

 </script>